### ISSUE TITLE
Group 3: Evan, Wayne, & Winters-- Nav Bar set-up

### ISSUE THREAD

**Issue by EvanSolisBoiseState** [AlisaMarie/AlisaMarie.github.io#1]
When we were playing around with the Nav bar, we noticed that it seemed on first appearance that it was one long, odd link. When hovered over we realized it was multiple. We feel that adding some small padding between Nav Bar links would help clarify that these are separate things and ease usability.

**Comment by AlisaMarie** [comment]
Yeah, it was bootstrap that messed it up. it was fine before bootstrap so nicked bootstrap now.
