### ISSUE TITLE
Group 3: Wayne, Evan, & Winters-- Styling

### ISSUE THREAD

**Issue by EvanSolisBoiseState** [AlisaMarie/AlisaMarie.github.io#2]
We really liked your theme. Its very visually appealing. However, we feel that there could me some more dynamic parts to it, specifically in regards to foreground background styling. It may help the website feel more centered by putting the images in a static background and the text in a dynamic foreground.

**Comment by AlisaMarie** [comment]
Oh totally agreed! i just hadn't gotten to it yet. Along with that, added in some more content, resized things, changed some things, ya know, the works.
